# Generated by Django 4.0.4 on 2022-04-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lowest_bidder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
