# Generated by Django 4.0.4 on 2022-04-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_lowest_bidder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='lowest_bidder',
            new_name='lowest_bidder_id',
        ),
        migrations.AddField(
            model_name='item',
            name='lowest_bidder_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='currentPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
