# Generated by Django 4.0.4 on 2022-05-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_lowest_bidder_item_lowest_bidder_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currentPrice',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
