# Generated by Django 4.0.4 on 2022-05-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_currentprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='basePrice',
            field=models.PositiveIntegerField(),
        ),
    ]
