# Generated by Django 4.0.4 on 2022-05-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_baseprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='myPrice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='lowest_bidder_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='mobile',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
